### PR TITLE
Refresh Render Issue Solved

### LINKED ISSUE #400: [Bug]: Refresh Rendering of Pages not Working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The pages don't render sometimes and shows up error

### Expected behavior

All the websites routes should render properly

### Add screenshots (if applicable)

image
Usually shows up after a refresh sometimes even without a refresh

### On which device or platform are you experiencing this bug?

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

### PR DESCRIPTION
**Pull request by NK-Works**
# Title and Issue number

**Title: Refresh Rendering of Pages not Working**

**Issue No.:**

Close #400 

---

# Screenshots/Video (mandatory)

Video only possible after deployment.... So can't make it you can first test it once then go with merging

---

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [ ] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [ ] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Anuj3553** [comment]
Please give the video of your work.

**Comment by NK-Works** [comment]
Here's the video:
https://github.com/user-attachments/assets/612a5aae-4aad-4088-bb71-8f14bd4e2567

Even after multiple refreshes the page renders.

**Comment by Anuj3553** [comment]
> Here's the video:
> 
>  Screen.Recording.2024-11-07.101729.mp4 
> Even after multiple refreshes the page renders.

Okk first i have to test then after i can merge this PR.

**Comment by NK-Works** [comment]
👍

**Comment by Anuj3553** [comment]
Well done @NK-Works

**Pull request merged**
