### PR TITLE
redesign login/sign

### PR DESCRIPTION
**Pull request by Hh440**
issue:#2

- created Login and SignUp page. 
- removed the navigation bar form the login and signup page to give them more impactful visuals.

### CODE REVIEW

**Comment by Anuj3553** [comment]
Navbar isn't showing after switching from Bootstrap to Tailwind CSS, there are a few common reasons this might happen. 

Class Name Changes: Ensure you're using the correct Tailwind CSS utility classes. Tailwind doesn't use predefined component classes like Bootstrap. For example:

Replace navbar, navbar-expand-lg, navbar-brand, etc., with Tailwind classes such as flex, justify-between, items-center, bg-gray-800, etc.
Flexbox and Positioning: Tailwind relies heavily on Flexbox. Make sure you're using Flexbox classes appropriately to manage layout. For example:

jsx
Copy code
<nav className={`flex items-center justify-between p-4 bg-${mode === 'dark' ? 'black' : 'white'}`}>
Conditional Classes: If you're conditionally applying classes based on the mode, ensure the syntax is correct. Tailwind doesn't recognize Bootstrap's way of applying styles. Instead of something like navbar-${mode}, you might want to use:

jsx
Copy code
`bg-${mode === 'dark' ? 'black' : 'white'}`
Missing Styles: Confirm that Tailwind CSS is properly configured in your project. Check that:

Tailwind is included in your CSS file (e.g., @tailwind base;, @tailwind components;, @tailwind utilities;).
You have the correct PostCSS setup (if you're using a build tool).
Responsive Design: Make sure your responsive classes are applied correctly. For example, instead of navbar-expand-lg, you might want to use Tailwind's responsive utility classes like md:flex, hidden, etc.

JS Functionality: If you were relying on Bootstrap's JavaScript for dropdowns or collapsible elements, you might need to implement this functionality manually or use a library that works with Tailwind, as Tailwind doesn't come with built-in JS.

Tailwind Configuration: If you have a custom Tailwind configuration, ensure that your theme and variants are set up correctly to include the classes you're trying to use.

This is full code solution -> 

import { useEffect, useState } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import PropTypes from 'prop-types';
import axios from 'axios';
import AddProject from './AddProject';
import logo from '../assets/images/logo.png';
import avatarDropdown from '../assets/images/Dropdown/avatar.png';
import { auth } from '../component/Firebase/Setup';

function Navbar(props) {
    const host = "http://localhost:5000";
    const navigate = useNavigate();
    const location = useLocation();
    const { title, home, community, discussion, about, mode, toggleMode, showAlert } = props;
    const [isScrolled, setIsScrolled] = useState(false);
    const [image, setImage] = useState(null);
    const [imageError, setImageError] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            setIsScrolled(window.scrollY > 50);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    useEffect(() => {
        axios.get(`${host}/getAvatarImage`)
            .then(res => {
                setImage(res.data[res.data.length - 1].image);
            })
            .catch(err => {
                setImageError(true);
                console.log(err);
            });
    }, [host]);

    const renderUploadButton = () => {
        if (location.pathname === '/myprofile') {
            return <AddProject mode={mode} showAlert={showAlert} />;
        }
        return null;
    };

    const handleLogout = async () => {
        if (window.confirm("Are you sure you want to log out?")) {
            try {
                await auth.signOut();
                localStorage.removeItem('token');
                navigate('/login');
            } catch (error) {
                console.error(error);
            }
        }
    };

    return (
        <nav className={`flex items-center justify-between p-4 ${isScrolled ? 'bg-gray-800' : 'bg-transparent'} transition-all duration-300`}>
            <div className="flex items-center">
                logo
                <span className={`ml-2 text-lg font-bold ${mode === 'dark' ? 'text-white' : 'text-black'}`}>{title}</span>
            </div>
            <div className="flex space-x-4">
                <Link to="/" className={`text-lg ${location.pathname === '/' ? 'text-blue-500' : (mode === 'dark' ? 'text-white' : 'text-black')}`}>{home}</Link>
                <Link to="/about" className={`text-lg ${location.pathname === '/about' ? 'text-blue-500' : (mode === 'dark' ? 'text-white' : 'text-black')}`}>{about}</Link>
                <Link to="/community" className={`text-lg ${location.pathname === '/community' ? 'text-blue-500' : (mode === 'dark' ? 'text-white' : 'text-black')}`}>{community}</Link>
                <Link to="/discussion" className={`text-lg ${location.pathname === '/discussion' ? 'text-blue-500' : (mode === 'dark' ? 'text-white' : 'text-black')}`}>{discussion}</Link>
            </div>
            <div className="flex items-center">
                {!localStorage.getItem('token') ? (
                    <>
                        <Link to='/login' className="btn btn-primary mx-2 text-white bg-blue-600 px-4 py-2 rounded">Login</Link>
                        <Link to='/signup' className="btn btn-primary mx-2 text-white bg-blue-600 px-4 py-2 rounded">Signup</Link>
                    </>
                ) : (
                    <>
                        {renderUploadButton()}
                        <div className="relative">
                            <button onClick={toggleMode} className="p-2 text-lg">
                                {mode === 'dark' ? '🌙' : '☀️'}
                            </button>
                            avatar
                            <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg">
                                <Link to="/myprofile" className="block px-4 py-2 text-black">My Profile</Link>
                                <Link to="/editprofile" className="block px-4 py-2 text-black">Edit Profile</Link>
                                <hr />
                                <a onClick={handleLogout} className="block px-4 py-2 text-black cursor-pointer">Logout</a>
                            </div>
                        </div>
                    </>
                )}
            </div>
        </nav>
    );
}

Navbar.propTypes = {
    title: PropTypes.string.isRequired,
    home: PropTypes.string.isRequired,
    community: PropTypes.string.isRequired,
    discussion: PropTypes.string.isRequired,
    about: PropTypes.string.isRequired,
    mode: PropTypes.string.isRequired,
    toggleMode: PropTypes.func.isRequired,
    showAlert: PropTypes.func.isRequired,
};

export default Navbar;

**Comment by Anuj3553** [comment]
Hyy @Hh440 ,

The Signup and Sign in is not working. It supposed to do. Check your frontend code and match with the original as well as check frontend part also it have to responsive. 

Time to time check console and network tab in the developers tools. If you have any questions or additional information, free feel to add them here. Your contributions are highly appreciated 😊.

Bitbox Responsiveness

Bitbox Console

**Comment by Hh440** [comment]
https://github.com/user-attachments/assets/65973a37-18fb-47c6-a35a-59f83c23dbc6

-  The SignUp and LogIn functionalities are working perfectly. 
- I encountered issues with the MongoDB URL provided for production; therefore, I replaced it with my own MongoDB URL.

**Comment by Anuj3553** [comment]
Congratulation @Hh440 on your successful contribution! 🎉
You've earned the labels gssoc-ext, hacktoberfest-accepted, and level1.
Great job on fixing the MongoDB URL and ensuring the SignUp and LogIn functionalities are working smoothly! Keep up the excellent work and continue contributing to make your projects even better.

**Comment by Hh440** [comment]
hacktoberfest label was not added so they are not accepting my contribution

**Pull request merged**
