### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by Pushpa472**
# Title and Issue number

**Title: Improving UI design of contribution page

**Issue No.: #348

Close #398

# Screenshots/Video (mandatory)

before:
image
after
image

before:
image
after
image

before
image
after
image

before
Screenshot 2024-11-06 111715
after
image

I added margin to the top and bottom of the feedback page for better spacing.

# Checklist:
- [x ] I have mentioned the issue number in my Pull Request.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [x ] I'm a GSSOC-EXT contributor
- [x ] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Pushpa472** [comment]
image

**Comment by Anuj3553** [comment]
Still there is conflicts -> 
image

**Comment by Anuj3553** [comment]
Hyy there is some conflicts -> 

image

**Comment by Pushpa472** [comment]
@Anuj3553 how i can resolve... resolve conflict button is disable

**Comment by Anuj3553** [comment]
> @Anuj3553 how i can resolve... resolve conflict button is disable

You can pull the code before saving your code and then push it.

**Comment by Anuj3553** [comment]
> @Anuj3553 in above given conflict file should i edit it and again I create pull request. other wise my PR will not be merge today is last day to submit unmerge PR pending.

Make another PR and raised it. You can close this PR and make sure a vedio attached of your work.

**Comment by Pushpa472** [comment]
@Anuj3553 using this command git pull origin main I will get latest changes in code after.. again raising PR it will not be create conflict

**Comment by Pushpa472** [comment]
@Anuj3553 when i working on this repo i fork... that time should i delete it and again fork it ... because whatever i work on this i will lose my work.. 
in this repo i pull updates code but not got it.

**Comment by Anuj3553** [comment]
> @Anuj3553 when i working on this repo i fork... that time should i delete it and again fork it ... because whatever i work on this i will lose my work.. in this repo i pull updates code but not got it. plz tell me i have very less time to complete it.

Hyy @Pushpa472, You can delete the git file of your project so it breaks the connection with the git and make another folder and pull the code. So its makes easy for you check the code of your original and make modifications according to you in the another folder.

**Comment by Pushpa472** [comment]
@Anuj3553 I already done my work then also said me do again but now UI design not visible plz see it
Screenshot 2024-11-10 125514

**Comment by Anuj3553** [comment]
> @Anuj3553 I already done my work then also said me do again but now UI design not visible plz see it Screenshot 2024-11-10 125514

There are some conflicts so i said you to raise the New PR and make separate folder so you have your code safe then do the modification @Pushpa472

**Pull request closed without merging**
