### PR TITLE
added email reset link issue #60

### PR DESCRIPTION
**Pull request by AyushSharma72**
added an modal on the frontend and an api on the backend which lets user use the functionality of forgot password 

when the user fills email on the modal and press submit 
Screenshot (205)

image2:
Screenshot (206)

an email is sent with the url of forgot password page by which user can visit the page and reset the password 

advantage:
only the authenticated user will be able to reset the password as the email will go only to that user 

email will go like this:
WhatsApp Image 2024-10-11 at 12 55 15_c68ea24f

please add gssoc-ext and level3 label before merge

### CODE REVIEW

**Comment by Anuj3553** [comment]
Give me code of your two files. I'm getting confilict.
client/package-lock.json
server/routes/auth.js

Issue


Share on my whatsapp number -> 8081718102

**Comment by Anuj3553** [comment]
image

Hyy @AyushSharma72, Give me three files code.

**Comment by Anuj3553** [comment]
There are 3 files conflict provide me code so i can fix it.

image

**Comment by AyushSharma72** [comment]
> There are 3 files conflict provide me code so i can fix it.
> 
> image

I will give u files but what about this pr then ??

**Comment by Anuj3553** [comment]
> > There are 3 files conflict provide me code so i can fix it.
> > image
> 
> I will give u files but what about this pr then ?? Let me resolve the conflicts first I did a clean pr

Okk if you want to do yourself then go ahead. I want that only the new code will pasted down so all conflicts will get resolved.

**Comment by AyushSharma72** [comment]
> > > There are 3 files conflict provide me code so i can fix it.
> > > image
> > 
> > 
> > I will give u files but what about this pr then ?? Let me resolve the conflicts first I did a clean pr
> 
> Okk if you want to do yourself then go ahead. I want that only the new code will pasted down so all conflicts will get resolved.

i will create another pr

**Pull request closed without merging**
