### PR TITLE
Fixed glitching issues

### LINKED ISSUE #206: [Bug]: website glitching on community page and no navbar on login and signup pages.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi @Anuj3553 bro, I request you to please go through the PRS you are merging.

First of all the website on the deployment and on the local server are slightly different.

Second, I noticed that someone raised a PR for revamping signup and login components and they messed up the whole layout, right now the navbar is not even getting displayed in the login signup page.

I can solve all these issues under a lvl3 if you let me.

### Expected behavior

Proper UI

### Add screenshots (if applicable)

image

image

image

### On which device or platform are you experiencing this bug?

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

### PR DESCRIPTION
**Pull request by ShivanshPlays**
# Title and Issue number

**Title:** Solved several inconsistencies on the website, related ss are attached below.

**Issue No.:**

Close #206 

---

# Screenshots/Video (mandatory)

Screenshot 2024-10-23 041626
Screenshot 2024-10-23 042106
Screenshot 2024-10-23 042125
Screenshot 2024-10-23 222553

Now all those issues are solved as you can observe in the screen recording below:
https://github.com/user-attachments/assets/ce3cc530-4a04-4ee4-9049-26c0de46a0e1

---

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [x] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
Hi program manager here,  @Harshit7492 add level 2 label for this PR

**Comment by ShivanshPlays** [comment]
@MastanSayyad I appreciate the review policies, although may I know the reason for this deprecation? I think the the level is justified

**Comment by MastanSayyad** [comment]
hi @ShivanshPlays 

- Most of the code is formatted 
- have CSS modification with minor js logic which can be only applies as level 2

image

**Comment by Anuj3553** [comment]
> Hi program manager here, @Harshit7492 add level 2 label for this PR

Hyy @MastanSayyad, I'm changed the level2 from level3. Thankyou for reviewing the PR.

**Pull request merged**
