### PR TITLE
Added [Responsive-Footer]

### LINKED ISSUE #157: [Feature Request]: Improve the Footer Design on the Main Page
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

The current footer on the main page lacks clarity and responsiveness. It could be enhanced to improve usability and aesthetics, especially on smaller screens.

### What problem does this feature solve?

**Problem This Feature Solves:**
The current footer design presents several issues that impact usability and accessibility:

1. *Poor User Experience on Mobile Devices*: The footer is not fully responsive, leading to misalignment or cluttered content on smaller screens, making it hard for users to interact with important elements.
2. *Lack of Structure*: The footer lacks clear organization, causing users to struggle when finding essential information like contact details, useful links, or social media pages.
3. *Readability and Accessibility Concerns*: Insufficient spacing, small font sizes, and low contrast may cause readability issues, particularly for users with visual impairments or on mobile devices.
4. *Inconsistent Footer Visibility*: On longer pages, users must scroll to the bottom to access the footer. A sticky footer would provide a better experience by keeping key links always accessible.

By implementing this feature, the footer will be more user-friendly, accessible, and organized across all devices and screen sizes, improving the overall user experience.

**Suggested Improvements:**

- *Enhanced Responsiveness*: Ensure the footer adapts well to different screen sizes, especially on mobile devices. Elements should remain properly aligned and spaced.
-*Improved Layout*: Organize the footer content into distinct sections, such as:
"About Us"
"Contact Information"
"Useful Links"
"Social Media Links"
- *Sticky Footer*: Implement an option to make the footer sticky so that it remains visible at the bottom of the page as the user scrolls.
- *Increased Readability*: Improve padding, margin, and font sizes for better readability and accessibility, ensuring sufficient contrast between text and background.
- *Add Social Media Icons/Links*: Incorporate social media icons with quick links to platforms, as well as important links like "Terms of Service" and "Privacy Policy."

Examples of some reponsive footers - 
mobile
des

### Alternative solutions

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

### PR DESCRIPTION
**Pull request by anothercoder-nik**
# Title and Issue number

**Title: Improve the Footer Design on the Main Page**

**Issue No.:157**

Fixes #157

---

# Screenshots/Video (mandatory)

As now it is working fine for phone and tablets and also the UI of footer improved for better user experience for
both Dark Mode and Light Mode.
**LIGHT MODE**
fixed_design_language_light
**DARK MODE**
fixed_design_language_dark
**MOBILE RESPONSIVE**
fixed_mobile_1

---

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [X] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**
To enhance the mobile responsiveness and user interaction of your footer, adopt a mobile-first design using CSS Flexbox or Grid to ensure flexible layouts that stack vertically on smaller screens. Incorporate interactive elements like subtle hover effects on links and animated social media icons to engage users. Ensure accessible navigation by clearly labeling all links and using aria-label for icons. Integrate feedback mechanisms, such as a modal for user suggestions and a subscription link for updates, while improving typography with larger, legible fonts and contrasting colors for visibility. Adjust icon sizes and spacing for mobile taps, and consider a sticky footer that remains visible for easy access. Finally, gather user feedback to identify pain points and regularly test for usability, implementing CSS and JavaScript enhancements as needed.

**_Are you contributing under any Open-source programme?_**

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Harshit7492** [comment]
Well done @anothercoder-nik

**Comment by anothercoder-nik** [comment]
hey @Anuj3553 @Harshit7492, plz attach gssoc and hacktoberfest labels, because on leaderboard it is not counted yet even after latest update.

**Comment by anothercoder-nik** [comment]
please help!

**Comment by Anuj3553** [comment]
> please help!

Hyy @anothercoder-nik, Sorry for inconvenience to you. I have attached the labels to you. Well done @anothercoder-nik.

**Comment by anothercoder-nik** [comment]
Thanks @Anuj3553 man 😊!

**Comment by Anuj3553** [comment]
> Thanks @Anuj3553 man 😊!

Mention not @anothercoder-nik bro ✌️❤️

**Comment by anothercoder-nik** [comment]
I have raised a star on this project and also sent you linkedin request by name Nikunj Agarwal @Anuj3553

**Comment by Anuj3553** [comment]
> I have raised a star on this project and also sent you linkedin request by name Nikunj Agarwal @Anuj3553

Got it @anothercoder-nik

**Pull request merged**
