### PR TITLE
I have done changes in footer section to improve its appearance.

### PR DESCRIPTION
**Pull request by sayiamarora**
In this PR, I have enhanced the hover effects for the links and social media icons in the footer section. The changes include:

Added a smooth transform: scale(1.05) effect to all links within the footer, making them slightly larger when hovered over to improve user interaction and visual appeal.
Adjusted the social media icons with transform: scale(1.1) on hover, providing a more dynamic and engaging user experience.
Included transition properties for both transform and color to ensure smooth transitions between states.
Updated the dark mode styles to maintain readability, adjusting the hover colors to fit better with the dark theme.
These changes create a more appealing and user-friendly interface for the footer section, providing a consistent and polished look.

 I'm a GSSOC-EXT contributor
 I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by sayiamarora** [comment]
Hey @Anuj3553 Can you please review my pull request for the issue number #154

**Comment by Anuj3553** [comment]
> Hey @Anuj3553 Can you please review my pull request for the issue number #154

Sure :)

**Comment by Anuj3553** [comment]
Here are some conflicts in the Footer.css file. Can you check and push again?

image

**Comment by sayiamarora** [comment]
@Anuj3553 review the changes.

**Comment by Anuj3553** [comment]
Well done @sayiamarora.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Pull request merged**
