### PR TITLE
feat: Discussion page chat toggle

### LINKED ISSUE #200: [Feature Request]: change the discussion page to dark mode
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

change the dark mode effect in discussion page

### What problem does this feature solve?

the discussion page is too bright in dark mode , i will fix this.
Screenshot 2024-10-22 111919

### Alternative solutions

_No response_

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

### PR DESCRIPTION
**Pull request by AE-Hertz**
#  [Feature Request]: change the discussion page to dark mode #200 

**Title: [Feature Request]: change the discussion page to dark mode**

**Issue No.: #200 **

Close #200 

---

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [X] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory):**

**_Are you contributing under any Open-source programme?_**

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by AE-Hertz** [comment]
sending anther PR because of this merge conflict

**Comment by Harshit7492** [comment]
please add some visuals to foe better understandability @AE-Hertz what now changes look like

**Comment by Anuj3553** [comment]
image

Hyy @AE-Hertz check your conflicts

**Comment by AE-Hertz** [comment]
@Anuj3553 sir requested new PR #257  merge this first , and i am closing this PR

**Comment by Anuj3553** [comment]
> @Anuj3553 sir requested new PR #257 merge this first , and i am closing this PR

Merged Successfully 👍

**Pull request closed without merging**
