### PR TITLE
Implement GitHub PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes:** #146 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes #<issue-number>` or `Fixes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@Anuj3553

### CODE REVIEW

**Comment by Anuj3553** [comment]
Well done @smog-root

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by smog-root** [comment]
> Can you give star to this repo?

I already gave a star!

**Comment by Anuj3553** [comment]
> > Can you give star to this repo?
> 
> I already gave a star!
> 
> 
> 
> @Anuj3553

Thankyou bro ✌️

**Pull request merged**
