### PR TITLE
added forgot page

### PR DESCRIPTION
**Pull request by ganashree1612**
i have added forgot page review  the changes and accept the pull request

### CODE REVIEW

**Comment by Anuj3553** [comment]
Hyy @ganashree1612, 

Could you provide me screen recording and screenshots of your implementation.

**Comment by ganashree1612** [comment]
sure here is the implementation the ui will change if merged the previous pull request
[forgotpage.zip](https://github.com/user-attachments/files/17269102/forgotpage.zip)
here is the zip file which has screen recording
if the previous pull request is merged the ui will look like
Screenshot (106)

**Comment by Anuj3553** [comment]
Congratulations @ganashree1612 on successfully completing the issue! 🎉
Your contribution is greatly appreciated, and the updates you've made have been successfully implemented. Keep up the fantastic work and continue making valuable contributions!

**Comment by ganashree1612** [comment]
Can u please add gssoc labels

**Pull request merged**
