### PR TITLE
added cursor animation

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Anuj3553 
I have added cursor animation and made it align with the website styling
Kindly check it out
Please consider it as level2

issue no : #283 

https://github.com/user-attachments/assets/9968c28f-9762-418b-a7e3-5a63ef927f2f

### CODE REVIEW

**Comment by Anuj3553** [comment]
Hyy @AswaniBolisetti, There is some conflicts in App.jsx, Please check it.

**Comment by Anuj3553** [comment]
> @Anuj3553 I have added cursor animation and made it align with the website styling Kindly check it out Please consider it as level2
> 
> issue no : #283
> 
>  cursor6.mp4

For this level1 is justified label.

**Comment by AswaniBolisetti** [comment]
Kindly check now
Resolved the conflicts

**Comment by Anuj3553** [comment]
> Kindly check now Resolved the conflicts

Well done @AswaniBolisetti

**Comment by AswaniBolisetti** [comment]
> Can you give star to this repo?

Done

**Pull request merged**
