### PR TITLE
Fixed dark mode and light mode theme issues in footer, About Us segment, InputModal, Navbar and Login/Signup components; added PropTypes validation in About Us page and Discussions to prevent bugs, footer.

### PR DESCRIPTION
**Pull request by anothercoder-nik**
### Pull Request Description

**Title:** Fixes for Dark Mode and Light Mode Themes & Added PropTypes Validation

I’ve made some updates to improve our app’s appearance and stability. Here’s what I worked on:

1. **Theme Improvements:**
   - I fixed the dark mode and light mode themes in several areas, including:
     - The footer
     - The About Us section
     - The Navbar
     - The Login and Signup components
     - InputModal
   - Now, everything should look great whether you're in dark mode or light mode!

2. **PropTypes Validation:**
   - I added PropTypes validation to the About Us page and the Discussions component. This should help catch any bugs related to incorrect props being passed around, making our code more robust.

**Testing:**
- I tested everything to ensure that the theme toggle works seamlessly across the affected components.
- The PropTypes validation is in place, so we should see fewer runtime errors moving forward.

**Why This Matters:**
- With these changes, our app will provide a consistent and enjoyable experience for users.
- Plus, the added validation helps us write better code and catch potential issues early on.

Below are the fixes-
**Signup page**

https://github.com/user-attachments/assets/6c522854-405c-41e5-bbf6-468f946e6536

**About Us**

https://github.com/user-attachments/assets/deef9dad-de49-4e49-b083-2ca52ed776a1

**Nav Bar login|Signup button**

https://github.com/user-attachments/assets/e3febb59-714f-48e1-81d1-371851fc23fa

**InputModal Now Woking fine in Dark/Light Mode**

dark

light

Let me know if you have any questions or feedback!

### CODE REVIEW

**Comment by Anuj3553** [comment]
Hyy @anothercoder-nik, There are so many conflicts. Can you pull again the code and apply your updated features.

image

**Comment by anothercoder-nik** [comment]
Sure I will check again just not and will update it by today.

**Comment by Anuj3553** [comment]
> Sure I will check again just now and will update it by today.

Okk @anothercoder-nik

**Comment by anothercoder-nik** [comment]
hey @Anuj3553 , I cleared all the conflicts , its like someone else fixed some code which I did which got committed before me, but now I resolved it , kindly check soon please. Thanks for giving the opportunity to me.

**Comment by anothercoder-nik** [comment]
**Current Status**

conflict_resolved

**Comment by anothercoder-nik** [comment]
Thanks @Anuj3553 for giving the chance to let me contribute, Good Wishes to you!

**Pull request merged**
