### PR TITLE
Improved UI Design

### PR DESCRIPTION
**Pull request by Pushpa472**
# Title and Issue number

**Title: Improving UI design of contribution page

**Issue No.: #348 

Close #398 

# Screenshots/Video (mandatory)
before
image
after
image
before
image
after
image
before
image
after
image
before
image
after
image

I added margin to the top and bottom of the feedback page for better spacing.
I already added hover-effect on social media.

# Checklist:

- [ x] I have mentioned the issue number in my Pull Request.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have gone through the `contributing.md` file before contributing.

**_Are you contributing under any Open-source programme?_**

- [ x] I'm a GSSOC-EXT contributor
- [ x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Pushpa472** [comment]
@Anuj3553 here show again conflict plz enable the resolve conflict button so that i can resolve it

**Comment by Anuj3553** [comment]
> @Anuj3553 here show again conflict plz enable the resolve conflict button so that i can resolve it

There is no option to enable the button - 

Screenshot_20241110_180944

**Comment by Pushpa472** [comment]
@Anuj3553 then this work will not show my contribution

**Comment by Pushpa472** [comment]
@Anuj3553 hey what about my PR

**Comment by Anuj3553** [comment]
> @Anuj3553 hey what about my PR

Unfortunately the event is ended and you have to clear your conflicts but there are still conflict and I'm also do nothing for this. Request the event management for this issue.

**Pull request closed without merging**
